<div class="page-header text-center">
    <h1>Task Management App</h1>
</div>

<form class="form-inline text-center" action="<?= '../update/'.$data->id ?>" method="post">
    <div class="form-group">
        <label class="sr-only">Task Name</label>
        <input type="text" class="form-control" placeholder="Input task name" name="name" value="<?= $data->name ?>">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
